name: OP-ACE-5
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-opace5-kernelsu-susfs:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OP-ACE-5"
      soc: "pineapple"
      branch: "oneplus/sm8650"
      manifest: "oneplus_ace5.xml"
      android_version: "android14"
      kernel_version: "6.1"
