name: OP-ACE-2
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-opace2-kernelsu-susfs:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OP-ACE-2"
      soc: "waipio"
      branch: "oneplus/sm8475"
      manifest: "oneplus_ace2_v.xml"
      android_version: "android13"
      kernel_version: "5.10"
