name: OP-ACE-2-PRO
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-opace2pro-kernelsu-susfs:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OP-ACE-2-PRO"
      soc: "kalama"
      branch: "oneplus/sm8550"
      manifest: "oneplus_ace2pro_v.xml"
      android_version: "android13"
      kernel_version: "5.15"
